#!/bin/sh /etc/rc.common

USE_PROCD=1
START=10
STOP=90

CONFIG=simcard

start_service() {
	# Reading config file
	config_load ${CONFIG}

	procd_open_instance
	procd_set_param command /usr/sbin/simcard
	# /etc/init.d/dualsim reload will restart the daemon if this file has changed
	procd_set_param file /etc/config/simcard
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user root
	# respawn automatically if service died
	procd_set_param respawn ${respawn_timeout:-60}
	# write a pid file on instance start and remove it on stop
	procd_set_param pidfile /var/run/simcard.pid
	procd_close_instance
}

service_triggers() {
        procd_add_reload_trigger "simcard"
}

